# Generated by Django 3.0.8 on 2020-08-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockName', models.TextField()),
                ('StockSymbol', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('SMA25', models.FloatField()),
                ('SMA50', models.FloatField()),
                ('RSI', models.FloatField()),
            ],
            options={
                'db_table': 'TechnicalIndicators',
                'unique_together': {('StockSymbol', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='StockBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=30)),
                ('Date', models.DateField()),
                ('PrevClose', models.FloatField()),
                ('Open', models.FloatField()),
                ('Close', models.FloatField()),
                ('Low', models.FloatField()),
                ('High', models.FloatField()),
                ('VWAP', models.FloatField()),
                ('Volume', models.FloatField()),
                ('DeliveryPercent', models.FloatField()),
            ],
            options={
                'db_table': 'StockBasicInfo',
                'unique_together': {('Symbol', 'Date')},
            },
        ),
    ]
