# Generated by Django 3.0.8 on 2020-08-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalAnalysis', '0002_stocklastupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocklastupdate',
            old_name='UpdateDate',
            new_name='LastUpdateDate',
        ),
    ]
