# Generated by Django 3.0.8 on 2020-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalAnalysis', '0003_auto_20200804_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbasicinfo',
            name='Name',
            field=models.TextField(),
        ),
    ]
